[project]
name = "condition-diffusion-v5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "torch==2.6.0+cu118",
    "torchvision==0.21.0+cu118",
    "accelerate==1.10.1",
    "einops==0.8.1",
    "ema-pytorch==0.7.7",
    "kornia==0.8.2",
    "matplotlib==3.9.4",
    "numpy==2.0.2",
    "packaging==25.0",
    "pillow==11.3.0",
    "pytorch-fid==0.3.0",
    "pyyaml==6.0.3",
    "scipy==1.13.1",
    "torchmetrics==1.8.2",
    "tqdm==4.67.1",
    "pywavelets>=1.6.0",
    "torch-fidelity>=0.4.0",
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu118" }
torchvision = { index = "pytorch-cu118" }
